name: Azure Pipelines

trigger:
- master
- staging

pool: main_pool

variables:
  python.version: '3.10.14'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: 'test'

stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build
  jobs:
  - job: BuildInfrastructure
    displayName: 'Build infrastructure'
    steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBByBaEbrJf+v9agEtM6g/LruTudlDznQ/Dca0BW/awH3/lX26tI/a6kDg90tOCOZIMotbavb3ABKJfkaDvFFGtI='
        sshKeySecureFile: 'id_rsa'

    - task: DownloadSecureFile@1
      name: public_key
      displayName: 'Download Public Key'
      inputs:
        secureFile: 'id_rsa.pub'
    #--------------------------------------------#  
    # Use Terraform to create the Infrastructure      
    # Install Terraform on the pipeline agent 
    - task: TerraformInstaller@0
      displayName: 'Terraform installation'
      inputs:
        terraformVersion: '1.9.4'
    
    # Run Terraform Init on the pipeline agent 
    - task: TerraformTaskV4@4
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/$(environmentName)'
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: 'udacity-ass3'
        backendAzureRmStorageAccountName: 'udacityass3'
        backendAzureRmContainerName: 'terraform-state'
        backendAzureRmKey: '$(environmentName).terraform.tfstate'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
        commandOptions: '-var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)" -var "client_id=$(client_id)" -var "client_secret=$(client_secret)"'

    - task: TerraformTaskV4@4
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # Run Terraform Apply
    - task: TerraformTaskV4@4
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/$(environmentName)'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
        commandOptions: '-var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)" -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "packer_image=$(packer_image)" -var "public_key_path=$(public_key.secureFilePath)"'

    - task: TerraformTaskV4@4
      displayName:  Terraform output
      inputs:
        provider: 'azurerm'
        command: 'output'
        showDebugOutput: true
        outFile: 'terraform_out.json'
        outputDirectory: '$(System.DefaultWorkingDirectory)'
        outputFormat: 'json'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/$(environmentName)'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

    - task: Bash@3
      displayName: Add VMs to environment
      inputs:
        targetType: 'inline'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        script: |
          cat terraform_out.json
          $VM_IP = $(jq '.vm_ip' terraform_out.json)
          echo $(TF_OUT_VM_IP)
          ssh azureuser@$(TF_OUT_VM_IP) "mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/3.243.1/vsts-agent-linux-x64-3.243.1.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x '$(command -v systemctl)' ]; then ./config.sh --environment --environmentname $(environmentName) --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/$(az_devops_org)/ --work _work --projectname $(az_devops_proj) --auth PAT --token $(az_devops_pat) --runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --environment --environmentname $(environmentName) --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/$(az_devops_org)/ --work _work --projectname $(az_devops_proj) --auth PAT --token $(az_devops_pat); ./run.sh; fi"
    
    #--------------------------------------------#
    # Selenium (UI) Test Suite - Archive the package  
    # "ArchiveFiles@2" picks up the web package and archives it.
    - task: ArchiveFiles@2
      displayName: 'Archive UI Tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automated-testing/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-ui_tests.zip'
    # Selenium Test Suite - Publish the package  
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-ui_tests.zip   # Same as the archiveFile artifact above. 
      displayName: 'Upload Package'
      artifact: ui-tests-artifact

    #--------------------------------------------#    
    # FakeRestAPI - Archive
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: /fake-rest-api
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-restapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-restapi.zip
      displayName: 'Upload FakeRestAPI Package'
      artifact: rest-api-artifact

    #--------------------------------------------#  
    # JMeter (Performance) Test Suite - Archive
    - task: ArchiveFiles@2
      displayName: 'Archive Performance testsuite'
      inputs:
        rootFolderOrFile: /automated-testing/jmeter
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-perf_tests.zip'
    # JMeter Test Suite - Publish    
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-perf_tests.zip
      displayName: 'Upload Performance testsuite Package'
      artifact: performance-tests-artifact

#--------------------------------------------#
# DEPLOYMENT STAGE
#--------------------------------------------#
- stage: Deploy
  jobs:
  #--------------------------------------------#  
  # Deploy FakeRestAPI Web App
  - deployment: RestAPI
    displayName: Rest APIs
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              appName: 'udacity-ass3-api-app-AppService'
              appType: webApp
              package: $(Pipeline.Workspace)/rest-api-artifact/$(Build.BuildId)-restapi.zip 
              
  #--------------------------------------------#  
  # Selenium | Functional UI Tests
  # ToDo: 
  - deployment: SeleniumUITests
    displayName: Execute Selenium Tests
    environment:
      name: $(environmentName)
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: ui-tests
            
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |           
                echo 'this is pre-built vm that comed with python3.10, selenium and chromium browser and chromium driver to run UI Tests'
                python3 ../ui-tests/functional_ui_test.py
                cat functional_ui_test_selenium.log

#--------------------------------------------#
# TEST STAGE
#--------------------------------------------#
- stage: Test
  jobs:
  - job: ExecuteTests
    displayName: Execute Tests
    steps:
    # Postman Data Validation Test Suite    
    - task: Bash@3
      displayName: Run Data Validation Tests
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: 'newman run validation_test.json -e staging.environment.json --reporters cli,junit --reporter-junit-export validation_test_result.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)/automated-testing/postman'
    # Postman Regression Test Suite    
    - task: Bash@3
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: 'newman run regression_test.json -e staging.environment.json --reporters cli,junit --reporter-junit-export regression_test_result.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)/automated-testing/postman'

    - task: Bash@3
      displayName: 'Endurance Test Suite'
      inputs:
        targetType: 'inline'
        script: |
          jmeter -n \
            -t automated-testing/jmeter/endurance_test_suite.jmx \
            -l endurance-test-report/endurance-results.jtl \
            -e \
            -o endurance-test-report
    
    - task: publishhtmlreport@1
      displayName: 'Publish Endurance Test Results'
      inputs:
        htmlType: 'Jmeter'
        JmeterReportsPath: '$(Build.DefaultWorkingDirectory)/endurance-test-report'    

    - task: Bash@3
      displayName: 'Stress Test Suite'
      inputs:
        targetType: 'inline'
        script: |
          jmeter -n \
            -t automated-testing/jmeter/stress_test_suite.jmx \
            -l stress-test-report/stress-results.jtl \
            -e \
            -o stress-test-report

    - task: PublishTestResults@1
      displayName: 'Publish Stress Test Results'
      inputs:
        htmlType: 'Jmeter'
        JmeterReportsPath: '$(Build.DefaultWorkingDirectory)/stress-test-report'

    # ToDo: Complete the task as explained here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml#yaml-snippet
    - task: PublishTestResults@2
      displayName: Publish Tests Result
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*_result.xml'
        searchFolder: '$(Build.DefaultWorkingDirectory)'
        mergeTestResults: true
        testRunTitle: 'system_test'